services:
    register-api:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
            secrets:
              - auth_toml
        volumes:
            - ./:/src
        secrets:
          - source: auth_toml
            target: /home/app/.config/pypoetry/auth.toml
        ports:
            - 8507:8507
        networks:
            - gfmodules-qualification
            - zmodules

secrets:
  auth_toml:
    file: ./auth.toml

networks:
  gfmodules-qualification:
    driver: bridge
    name: gfmodules-qualification
  zmodules:
    driver: bridge
    name: zmodules