version: "3.5"

services:
    register-api:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        volumes:
            - ./:/src
        ports:
            - 8507:8507
        networks:
            - gfmodules-qualification

networks:
  gfmodules-qualification:
    driver: bridge
    name: gfmodules-qualification
