name: Package python virtual env

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        python_version: ["3.11"]
    runs-on: ubuntu-22.04
    steps:
      - name: Configure git
        run: git config --global url."https://${{ secrets.REPO_READ_ONLY_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Build venv package
        uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/python-venv-package@main
        with:
          python_version: ${{ matrix.python_version }}
          package_file_name: gfmodules-qualification-register-api-private
